### ISSUE TITLE
怎么判断自己是被DNS劫持了？

### ISSUE THREAD

**Issue by hardyZhi** [tencentyun/httpdns-ios-sdk#1]
iOS 中怎么能简单判断自己是被DNS劫持了？我想先判断自己被劫持了，然后再走HttpDNS，没被劫持就不做任何改动，这样对程序影响最小。

**Comment by httpdns** [comment]
你的解析结果你自己知道吗？如果知道，那就比较一下看是否一致，但是这样也会存在是否精准调度的问题，比如，你如何控制不跨网等

**Comment by hardyZhi** [comment]
解析结果是指特定约定的解析结果还是解析后的IP？

**Comment by httpdns** [comment]
就是你们正确的IP

**Comment by hardyZhi** [comment]
iOS local怎么简单获取当前域名的解析后的iP？

**Comment by hardyZhi** [comment]
getaddrinfo好像能获取，但网络有异常时，经常卡住

**Comment by httpdns** [comment]
是的，这个时候有可能是被劫持了，或者网络非常差，解析可以加个超时返回逻辑
