### ISSUE TITLE
模拟httpdns服务挂掉

### ISSUE THREAD

**Issue by ShenYj** [tencentyun/httpdns-ios-sdk#15]
如果想模拟httpdns挂掉的场景，改如何操作，是否可以提供服务器ip，我们修改下路由host，让我们访问httpdns服务失败，而达到测试的目的

**Comment by httpdns** [comment]
HTTPDNS作为域名解析服务，本身是和原生DNS技术类似，不是使用域名访问后台服务的；基于你的需求，可以考虑设置App不允许HTTP流量（Android/iOS在高版本上默认都是如此），来模拟HTTPDNS服务异常情况（iOS WGSetDnsAppKey接口需设置useHttp为YES）

**Comment by ShenYj** [comment]
如果我关闭ATS，那么App的所有请求都挂掉了，我只是想验证下当httpDns功能挂掉的情况下（一开始的初始化就挂掉，看文档当解析出错的情况下，会返回[0,0]），我是否还能正常使用域名的方式进行请求

**Comment by httpdns** [comment]
HTTPDNS SDK会使用LocalDNS解析结果作为兜底，在HTTPDNS服务异常时，如果LocalDNS能正常返回解析结果，SDK接口会将LocalDNS解析结果返回。从模拟HTTPDNS服务异常角度，似乎没有别的什么可行方法，可以考虑通过写一个Demo，关闭ATS来验证；如果是为了模拟HTTPDNS SDK接口返回异常情况，可以再封装下SDK使用，修改返回值再返回给上层使用进行测试

**Comment by ShenYj** [comment]
我们服务器还是用的http，没有升级https，我在网上看了篇文章，提到目前移动端的httpDns功能，原理上是将DNS协议转换成了Http协议，但根据您的回复“HTTPDNS作为域名解析服务，本身是和原生DNS技术类似，不是使用域名访问后台服务的” + “HTTPDNS SDK会使用LocalDNS解析结果作为兜底，在HTTPDNS服务异常时，如果LocalDNS能正常返回解析结果”，那我是否可以理解为，当httpDns服务异常时，解析域名的时候，不会返回[0,0]， 而是使用localDNS解析出的ip返回，而这个ip可能存在劫持、污染的问题？

**Comment by httpdns** [comment]
是的，HTTPDNS服务异常情况下，会fallback到LocalDNS，SDK内部已经做了相关处理。所以返回值上，确实仍旧可能存在劫持风险
