### ISSUE TITLE
iOS SDK获取ssid信息内存泄漏

### ISSUE THREAD

**Issue by svenJamy** [tencentyun/httpdns-ios-sdk#18]
通过`CNCopyCurrentNetworkInfo`方法获ssid信息，100%内存泄漏，而且是在重复获取，使用的是CF对象，看起来释放有问题，可以使用`__bridge_transfer`对象转移所有权试试。

![image](https://user-images.githubusercontent.com/21276382/88619216-967f0000-d0cd-11ea-89e9-8cbe937cfca8.png)

**Comment by HuYuee** [comment]
可以更新最新版，看是否还有此类问题
