### ISSUE TITLE
initHeatMapWindow

### ISSUE THREAD

**Issue by ymsheng** [tencentyun/httpdns-ios-sdk#2]
这个方法可以使用吗？如何 使用，谢谢

**Comment by ymsheng** [comment]
还有一个关于流量统计的方法，调用 了[BeaconBaseInterface enableNetFlowRecord:YES];
NSLog(@"-----net flow==%ld",[BeaconBaseInterface getToDayUsedNetFlow]); 这个始终是0.

**Comment by httpdns** [comment]
Beacon是另一个团队开发的，具体使用可参考http://beacon.qq.com/home.htm
