### ISSUE TITLE
弱网情况下同步获取域名解析导致崩溃

### ISSUE THREAD

**Issue by witchnana** [tencentyun/httpdns-ios-sdk#31]
手机模拟弱网情况，频繁进行前后台切换很容易崩溃

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001db9cbe24 0x1db9c8000 + 15908
1   libdispatch.dylib             	0x00000001af6bd098 0x1af6b9000 + 16536
2   libdispatch.dylib             	0x00000001af6bd678 0x1af6b9000 + 18040
3   UnityFramework                	0x0000000103ed3164 -[MSDKDnsManager getHostsByNames:verbose:] + 1900
4   UnityFramework                	0x0000000103eed30c -[MSDKDns WGGetHostByName:] + 876

**Comment by HuYuee** [comment]
可以贴下同步获取域名的相关代码吗？能否提供下版本号？
