### ISSUE TITLE
[MSDKDnsService getDomainsDNSFromCache:] crash

### ISSUE THREAD

**Issue by zhanghesheng** [tencentyun/httpdns-ios-sdk#40]
MSDKDnsService调用getDomainsDNSFromCache解析是发生crash

<img width="679" alt="截屏2023-11-02 15 28 02" src="https://github.com/TencentCloud/httpdns-sdk-ios/assets/7437146/38d07616-3896-47f2-818c-10be340b3ec2">

**Comment by HuYuee** [comment]
能否提供下您的SDK版本？
