### ISSUE TITLE
version1.10.0crash

### ISSUE THREAD

**Issue by dlmlzz6** [tencentyun/httpdns-ios-sdk#43]
Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype: KERN_PROTECTION_FAILURE at 0x000000016d838000
Exception Codes: 0x0000000000000002, 0x000000016d838000
VM Region Info: 0x16d838000 is in 0x16d838000-0x16d83c000;  bytes after start: 0  bytes before end: 16383
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack                    16d7b0000-16d838000 [  544K] rw-/rwx SM=PRV  thread 15
--->  Stack Guard              16d838000-16d83c000 [   16K] ---/rwx SM=NUL  
      Stack                    16d83c000-16d8c4000 [  544K] rw-/rwx SM=PRV  
Termination Reason: SIGNAL 10 Bus error: 10
Terminating Process: exc handler [21923]

Thread 15 name:   Dispatch queue: com.apple.NSURLSession-delegate
Thread 15 Crashed:
0   libsystem_platform.dylib      	       0x20b1b4360 __bzero + 64
1   QK_ParentManager              	       0x1045b13b0 +[MSDKDnsInfoTool decryptUseDES:key:] + 488
2   QK_ParentManager              	       0x1045b6cf8 -[HttpsDnsResolver getDecryptStrWithResponseStr:] + 484
3   QK_ParentManager              	       0x1045b602c -[HttpsDnsResolver handleDataTaskSuccessWithData:domains:response:delegate:] + 740
4   QK_ParentManager              	       0x1045b5990 __73-[HttpsDnsResolver startDataTaskWithHttpDnsUrl:domains:timeOut:delegate:]_block_invoke + 220
5   CFNetwork                     	       0x1a440ca84 0x1a440c8a1 + 483
6   CFNetwork                     	       0x1a442a9a0 0x1a442a901 + 159
7   libdispatch.dylib             	       0x1ab2616a8 _dispatch_call_block_and_release + 31
8   libdispatch.dylib             	       0x1ab263300 _dispatch_client_callout + 19
9   libdispatch.dylib             	       0x1ab26a894 _dispatch_lane_serial_drain + 747
10  libdispatch.dylib             	       0x1ab26b3f8 _dispatch_lane_invoke + 431
11  libdispatch.dylib             	       0x1ab276004 _dispatch_root_queue_drain_deferred_wlh + 287
12  libdispatch.dylib             	       0x1ab275878 _dispatch_workloop_worker_thread + 403
13  libsystem_pthread.dylib       	       0x20b25d964 _pthread_wqthread + 287
14  libsystem_pthread.dylib       	       0x20b25da04 start_wqthread + 7

**Comment by HuYuee** [comment]
您好，能提供下复现的步骤吗？

**Comment by dlmlzz6** [comment]
代理模式下启动即crash





---Original---
From: ***@***.***&gt;
Date: Mon, Mar 25, 2024 14:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TencentCloud/httpdns-sdk-ios] version1.10.0crash (Issue #43)




 
您好，能提供下复现的步骤吗？

**Comment by HuYuee** [comment]
好的，这块我们会排期处理
