### ISSUE TITLE
duplicate symbol _freeMemory 

### ISSUE THREAD

**Issue by hxming2919** [tencentyun/httpdns-ios-sdk#5]
duplicate symbol _freeMemory in:
    /Users/myMac/Desktop/MyProject_XXX/Pods/ATSDK-Weex/ATSDK.framework/ATSDK(ATMemoryMonitor.o)
    /Users/myMac/Desktop/MyProject_XXX/MyProject/ClassLibs/HttpDNS/BeaconAPI_Base.framework/BeaconAPI_Base(BeaconDeviceUtil.o)
duplicate symbol _usedMemory in:
    /Users/myMac/Desktop/MyProject_XXX/Pods/ATSDK-Weex/ATSDK.framework/ATSDK(ATMemoryMonitor.o)
    /Users/myMac/Desktop/MyProject_XXX/MyProject/ClassLibs/HttpDNS/BeaconAPI_Base.framework/BeaconAPI_Base(BeaconDeviceUtil.o)

======
你好，使用framework会出现编译符重覆问题。

**Comment by httpdns** [comment]
ATSDK是什么SDK呢？里面是否也集成了Beacon包，所以导致的duplicate
