### ISSUE TITLE
 为啥在4g网络下可以获取hdns_ip和ldns_ip但是wifi下只能获取到ldns_ip

### ISSUE THREAD

**Issue by wubinfei** [tencentyun/httpdns-ios-sdk#7]
真机情况下 用4g网络可以获取hdns_ip和ldns_ip但是wifi下只能获取到ldns_ip，而用模拟器在wifi情况下是能获取到hdns_ip和ldns_ip的，请问下是为什么

**Comment by httpdns** [comment]
正常是没问题，你可以检查下你的wifi网络是否正常，也可以在你的wifi网络下测试下我们的IP 119.29.29.29，是否可以ping通，如果不行，看是否网络侧是否有限制，之前有碰到过类似案例，客户公司的出口网络对部分外网IP做了禁止策略
