### ISSUE TITLE
接入httpdns成功后，但是项目中的H5页面直接访问不了了？

### ISSUE THREAD

**Issue by wubinfei** [tencentyun/httpdns-ios-sdk#8]
我是在afnetworking中的 AFHTTPSessionManager中替换成host，而且接入成功了，但是项目里的wkwebview里的H5页面打不开了，另外我用NSURLProtocol拦截到h5的链接是原来的，但就不是显示不出来，不知道怎么回事

**Comment by httpdns** [comment]
据我了解，NSURLProtocol无法拦截WKWebView的请求，如果需要实现WKWebView的防劫持方案，会比较麻烦，我们这边暂时无法提供该场景的解决方案~
